### PR TITLE
Merge branch 'codegen-bene' into codegen

### PR DESCRIPTION
**Pull request by Nereuxofficial**
Added some things to constant pools but i am not quite sure if i accidentally reverted a change while merging.

### CODE REVIEW

**Comment by ArtInLines** [comment]
I will take a look at it at around 8 probably, if that's fine for you

**Comment by Nereuxofficial** [comment]
> I will take a look at it at around 8 probably, if that's fine for you

Absolutely. Take your time

**Review by Segelente — APPROVED** [review]
LGTM

**Review by Segelente — CHANGES_REQUESTED** [review]
Doesnt build:

Cannot move twice and a few non-exhaustive patterns

**Review by ArtInLines — APPROVED** [review]
Looks good to me too. I would recommend merging the latest changes from `testing` because some of the tests are currently only failing because I made some mistakes in them that are only fixed on the testing-branch

**Comment by Nereuxofficial** [comment]
> Looks good to me too. I would recommend merging the latest changes from `testing` because some of the tests are currently only failing because I made some mistakes in them that are only fixed on the testing-branch

Sounds like a good idea. I now merged testing into the branch and am gonna merge the PR now and we'll have the newest changes in the codegen branch too

**Pull request merged**
